import type { Metadata } from "next";
import Link from "next/link";
import Image from "next/image";
import { notFound } from "next/navigation";
import { getTruck, trucks } from "@/content/trucks";
import { Breadcrumbs, Container, CtaBand, JsonLd, PageHero, SectionHeading } from "@/components/ui/Shared";
import { absoluteUrl } from "@/lib/site-url";
import { breadcrumbSchema, createMetadata } from "@/lib/seo";

export function generateStaticParams() { return trucks.map(({ slug }) => ({ slug })); }
export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> { const { slug } = await params; const truck = getTruck(slug); if (!truck) return {}; return createMetadata({ title: truck.seoTitle, description: truck.seoDescription, path: `/trucks/${slug}` }); }

export default async function TruckPage({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params; const truck = getTruck(slug); if (!truck) notFound();
  const crumbs = [{ name: "Home", path: "/" }, { name: "Trucks", path: "/trucks" }, { name: truck.name, path: `/trucks/${slug}` }];
  const productSchema = { "@context": "https://schema.org", "@type": "Product", name: truck.name, description: truck.summary, category: truck.category, url: absoluteUrl(`/trucks/${slug}`), brand: { "@type": "Brand", name: "Hino" } };
  return <><Container><Breadcrumbs items={[{ label: "Home", href: "/" }, { label: "Trucks", href: "/trucks" }, { label: truck.name }]} /></Container><PageHero eyebrow={truck.category} title={`${truck.name} in Cebu`} description={truck.positioning}><Link className="button" href={`/quote?model=${truck.slug}`}>Request a {truck.name} Quote</Link><Link className="button button-outline" href="/financing">Ask About Financing</Link></PageHero>
    <section className="section"><Container className="split"><div><SectionHeading eyebrow="Practical positioning" title="Choose around the operation" description={truck.summary} /><ul className="feature-list">{truck.uses.map((use) => <li key={use}>{use}</li>)}</ul><a className="text-link" href={truck.sourceUrl} target="_blank" rel="noreferrer">{truck.sourceLabel} ↗</a><p><small>Specifications reviewed {truck.lastReviewed}. Confirm current model and Cebu availability before purchase.</small></p></div><div className="official-image official-image-large"><Image src={truck.heroImage} alt={`${truck.name} Series official Hino Motors Philippines image`} fill priority sizes="(max-width: 720px) 100vw, 50vw" /></div></Container></section>
    <section className="section alt"><Container><SectionHeading eyebrow="Common applications" title="Plan the body and platform together" description="These are conversation starters, not a confirmation that every body or configuration is available or suitable." /><div className="grid grid-4">{truck.applications.map((application) => <article className="card card-body" key={application}><h3>{application}</h3><p>Review cargo, payload, dimensions, routes, and operational requirements with the team.</p></article>)}</div></Container></section>
    <section className="section"><Container className="split"><div><SectionHeading eyebrow="Key details" title="Official Philippine specifications" /><div className="detail-list">{truck.details.map((detail) => <div className="detail-row" key={detail.label}><strong>{detail.label}</strong><span>{detail.value}</span></div>)}</div><p><small>Figures are national published specifications and vary by model. They do not confirm local stock, body compatibility, payload suitability, or current availability.</small></p></div><div className="list-panel"><h3>Published model lineup</h3><ul className="feature-list">{truck.variants.map((variant) => <li key={variant}>{variant}</li>)}</ul>{truck.brochureUrl && <a className="text-link" href={truck.brochureUrl} target="_blank" rel="noreferrer">View an official brochure ↗</a>}</div></Container></section>
    <section className="section dark"><Container><SectionHeading eyebrow="Ownership support" title="Connect sales with service, parts, and financing" /><div className="grid grid-3">{[{ title: "Service support", href: "/service", copy: "Request a service schedule for team confirmation." }, { title: "Genuine parts", href: "/parts", copy: "Send vehicle and part details for review." }, { title: "Financing inquiry", href: "/financing", copy: "Discuss financing intent without implied approval or terms." }].map((item) => <article className="card card-body" key={item.title}><h3>{item.title}</h3><p>{item.copy}</p><Link className="text-link" href={item.href}>Get started →</Link></article>)}</div></Container></section>
    <section className="section"><Container><SectionHeading eyebrow="Related reading" title="Prepare for a better truck conversation" /><p><Link className="text-link" href="/guides">Browse the Cebu Truck Guide →</Link></p><div className="faq-list"><SectionHeading eyebrow="Questions" title={`${truck.name} FAQ`} />{truck.faqs.map((faq) => <details key={faq.question}><summary>{faq.question}</summary><p>{faq.answer}</p></details>)}</div></Container></section><CtaBand title={`Ask about the ${truck.name}`} href={`/quote?model=${truck.slug}`} label="Request a Quote" /><JsonLd data={breadcrumbSchema(crumbs)} /><JsonLd data={productSchema} /></>;
}
