import Link from "next/link";
import Image from "next/image";
import type { LeadType } from "@/lib/leads/types";
import { LeadForm } from "@/components/forms/LeadForm";
import { Breadcrumbs, Container, PageHero, SectionHeading } from "@/components/ui/Shared";

export function InquiryPage({ type, eyebrow, title, description, formTitle, submitLabel, points, note, defaults, image, officialSummary, officialPoints = [], sourceUrl }: { type: LeadType; eyebrow: string; title: string; description: string; formTitle: string; submitLabel: string; points: string[]; note: string; defaults?: Record<string, string>; image?: string; officialSummary?: string; officialPoints?: string[]; sourceUrl?: string }) {
  return <><Container><Breadcrumbs items={[{ label: "Home", href: "/" }, { label: title }]} /></Container><PageHero eyebrow={eyebrow} title={title} description={description} />{image && <section className="section alt"><Container className="split"><div className="official-image official-image-large"><Image src={image} alt={`Official Hino Motors Philippines ${title} image`} fill sizes="(max-width: 720px) 100vw, 50vw" /></div><div><SectionHeading eyebrow="Hino Philippines program" title="National support, connected locally" description={officialSummary} />{officialPoints.length > 0 && <ul className="feature-list">{officialPoints.map((point) => <li key={point}>{point}</li>)}</ul>}{sourceUrl && <a className="text-link" href={sourceUrl} target="_blank" rel="noreferrer">View official Hino Philippines source ↗</a>}<p><small>National program information was reviewed August 18, 2026. Confirm Cebu applicability, availability, and terms with the branch.</small></p></div></Container></section>}<section className="section"><Container className="split"><div><SectionHeading eyebrow="How it works" title="Send details for team review" /><ul className="feature-list">{points.map((point) => <li key={point}>{point}</li>)}</ul><div className="list-panel"><strong>Important</strong><p>{note}</p></div><p>Prefer to speak with the team? <Link className="text-link" href="/contact">View branch contact details →</Link></p></div><LeadForm type={type} title={formTitle} submitLabel={submitLabel} defaults={defaults} /></Container></section></>;
}
